#ifndef CRYPT64_CONFIGURATION
#define CRYPT64_CONFIGURATION

#define USE_COMMANDLINER (1)
#define USE_JUNKYARD (1)
#define USE_STRINGPOOL (0)
#define USE_HEXSTRING (0)
#define USE_FOURCC (1)
#define USE_BASE64 (1)
#define USE_CRYPT64 (1)
#define USE_TOKKEN (1)

#define SET_MAX_NAMELENGTH 255
#define SET_MAX_NUMBERARGS 8

#endif
